spring.application.name=demo

# SendGrid Configuration
sendgrid.api-key=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
sendgrid.from-email=janardhaniit474@gmail.com

# RabbitMQ Configuration
# 'rabbitmq' matches the service name in docker-compose
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# MySQL Configuration
# 'db' matches the service name in docker-compose
# Database name updated to 'email_db' for simplicity
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/email_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect